require conf/distro/openbmc-phosphor.conf
require conf/distro/include/phosphor-isolation.inc

DISTRO = "canopy"
DISTRO_NAME = "CanopyBMC (based on Phosphor OpenBMC)"
DISTROOVERRIDES .= ":canopy"

# Build channels:
# dev               - Usually with debug tooling and more.
# release (default) - For production
#
CANOPY_CONFIG ?= "release"
OVERRIDES .= ":${CANOPY_CONFIG}:"

# Optional free-form tag appended to the version (e.g. "mybranch").
CANOPY_CUSTOM_TAG ?= ""

IMAGE_FEATURES:append = " allow-root-login"
