FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
SRC_URI += "file://0001-fansensor-support-TachInput-configuration-for-PWM-on.patch"
SRC_URI += "file://0002-fansensor-add-fan-fault-monitoring-via-hwmon-fault-a.patch"
SRC_URI += "file://0003-hwmontempsensor-add-platform-device-support.patch"
SRC_URI += "file://0004-psusensor-add-gxp_psu-to-sensorTypes-whitelist.patch"
SRC_URI += "file://0005-HwmonTempSensor-Add-support-for-SPD5118.patch"
ERROR_QA:remove = "patch-status"
